// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrixmul_matrixmul,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.422500,HLS_SYN_LAT=21,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=186,HLS_SYN_LUT=234,HLS_VERSION=2025_1}" *)

module matrixmul (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_0_address0,
        a_0_ce0,
        a_0_q0,
        a_1_address0,
        a_1_ce0,
        a_1_q0,
        a_2_address0,
        a_2_ce0,
        a_2_q0,
        a_3_address0,
        a_3_ce0,
        a_3_q0,
        b_0_address0,
        b_0_ce0,
        b_0_q0,
        b_1_address0,
        b_1_ce0,
        b_1_q0,
        b_2_address0,
        b_2_ce0,
        b_2_q0,
        b_3_address0,
        b_3_ce0,
        b_3_q0,
        res_address0,
        res_ce0,
        res_we0,
        res_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1:0] a_0_address0;
output   a_0_ce0;
input  [15:0] a_0_q0;
output  [1:0] a_1_address0;
output   a_1_ce0;
input  [15:0] a_1_q0;
output  [1:0] a_2_address0;
output   a_2_ce0;
input  [15:0] a_2_q0;
output  [1:0] a_3_address0;
output   a_3_ce0;
input  [15:0] a_3_q0;
output  [1:0] b_0_address0;
output   b_0_ce0;
input  [15:0] b_0_q0;
output  [1:0] b_1_address0;
output   b_1_ce0;
input  [15:0] b_1_q0;
output  [1:0] b_2_address0;
output   b_2_ce0;
input  [15:0] b_2_q0;
output  [1:0] b_3_address0;
output   b_3_ce0;
input  [15:0] b_3_q0;
output  [3:0] res_address0;
output   res_ce0;
output   res_we0;
output  [15:0] res_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln24_fu_307_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] add_ln49_fu_283_p2;
reg   [3:0] add_ln49_reg_402;
reg   [3:0] add_ln49_reg_402_pp0_iter1_reg;
reg   [3:0] add_ln49_reg_402_pp0_iter2_reg;
reg   [3:0] add_ln49_reg_402_pp0_iter3_reg;
wire   [0:0] icmp_ln26_fu_301_p2;
reg   [0:0] icmp_ln26_reg_427;
reg   [0:0] icmp_ln24_reg_432;
reg  signed [15:0] a_1_load_reg_441;
reg  signed [15:0] a_2_load_reg_446;
reg  signed [15:0] b_1_load_reg_461;
reg  signed [15:0] b_2_load_reg_466;
wire   [15:0] mul_ln46_1_fu_328_p2;
reg   [15:0] mul_ln46_1_reg_476;
wire   [15:0] mul_ln46_3_fu_332_p2;
reg   [15:0] mul_ln46_3_reg_481;
reg   [0:0] ap_phi_mux_icmp_ln264_phi_fu_198_p4;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln24_fu_255_p1;
wire   [63:0] zext_ln26_fu_271_p1;
wire   [63:0] zext_ln49_1_fu_336_p1;
reg   [3:0] indvar_flatten1_fu_66;
wire   [3:0] add_ln24_1_fu_295_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten1_load;
reg   [2:0] i2_fu_70;
wire   [2:0] i_fu_243_p3;
reg   [2:0] ap_sig_allocacmp_i2_load;
reg   [2:0] j3_fu_74;
wire   [2:0] j_fu_289_p2;
reg   [2:0] ap_sig_allocacmp_j3_load;
reg    a_0_ce0_local;
reg    a_1_ce0_local;
reg    a_2_ce0_local;
reg    a_3_ce0_local;
reg    b_0_ce0_local;
reg    b_1_ce0_local;
reg    b_2_ce0_local;
reg    b_3_ce0_local;
reg    res_we0_local;
(* use_dsp48 = "no" *) wire   [15:0] add_ln46_2_fu_340_p2;
reg    res_ce0_local;
wire   [2:0] add_ln24_fu_229_p2;
wire   [1:0] trunc_ln24_fu_251_p1;
wire   [2:0] select_ln24_fu_235_p3;
wire   [3:0] tmp_fu_263_p3;
wire   [3:0] zext_ln49_fu_279_p1;
wire  signed [15:0] add_ln46_2_fu_340_p0;
wire   [15:0] grp_fu_345_p3;
wire  signed [15:0] add_ln46_2_fu_340_p1;
wire   [15:0] grp_fu_353_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_372;
reg    ap_condition_138;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 indvar_flatten1_fu_66 = 4'd0;
#0 i2_fu_70 = 3'd0;
#0 j3_fu_74 = 3'd0;
#0 ap_done_reg = 1'b0;
end

matrixmul_mul_16s_16s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mul_16s_16s_16_1_1_U1(
    .din0(b_2_load_reg_466),
    .din1(a_2_load_reg_446),
    .dout(mul_ln46_1_fu_328_p2)
);

matrixmul_mul_16s_16s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mul_16s_16s_16_1_1_U2(
    .din0(b_1_load_reg_461),
    .din1(a_1_load_reg_441),
    .dout(mul_ln46_3_fu_332_p2)
);

matrixmul_mac_muladd_16s_16s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_16s_16s_16ns_16_4_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_3_q0),
    .din1(a_3_q0),
    .din2(mul_ln46_1_reg_476),
    .ce(1'b1),
    .dout(grp_fu_345_p3)
);

matrixmul_mac_muladd_16s_16s_16ns_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_16s_16s_16ns_16_4_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_0_q0),
    .din1(a_0_q0),
    .din2(mul_ln46_3_reg_481),
    .ce(1'b1),
    .dout(grp_fu_353_p3)
);

matrixmul_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_138)) begin
        i2_fu_70 <= i_fu_243_p3;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_138)) begin
    indvar_flatten1_fu_66 <= add_ln24_1_fu_295_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_138)) begin
    j3_fu_74 <= j_fu_289_p2;
end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_1_load_reg_441 <= a_1_q0;
        a_2_load_reg_446 <= a_2_q0;
        add_ln49_reg_402 <= add_ln49_fu_283_p2;
        add_ln49_reg_402_pp0_iter1_reg <= add_ln49_reg_402;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        b_1_load_reg_461 <= b_1_q0;
        b_2_load_reg_466 <= b_2_q0;
        icmp_ln24_reg_432 <= icmp_ln24_fu_307_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln49_reg_402_pp0_iter2_reg <= add_ln49_reg_402_pp0_iter1_reg;
        add_ln49_reg_402_pp0_iter3_reg <= add_ln49_reg_402_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        mul_ln46_1_reg_476 <= mul_ln46_1_fu_328_p2;
        mul_ln46_3_reg_481 <= mul_ln46_3_fu_332_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln26_reg_427 <= icmp_ln26_fu_301_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_0_ce0_local = 1'b1;
    end else begin
        a_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_1_ce0_local = 1'b1;
    end else begin
        a_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_2_ce0_local = 1'b1;
    end else begin
        a_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_3_ce0_local = 1'b1;
    end else begin
        a_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln24_fu_307_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter4_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_372)) begin
            ap_phi_mux_icmp_ln264_phi_fu_198_p4 = icmp_ln26_reg_427;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln264_phi_fu_198_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln264_phi_fu_198_p4 = icmp_ln26_reg_427;
        end
    end else begin
        ap_phi_mux_icmp_ln264_phi_fu_198_p4 = icmp_ln26_reg_427;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i2_load = 3'd0;
    end else begin
        ap_sig_allocacmp_i2_load = i2_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten1_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten1_load = indvar_flatten1_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j3_load = 3'd0;
    end else begin
        ap_sig_allocacmp_j3_load = j3_fu_74;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_0_ce0_local = 1'b1;
    end else begin
        b_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_1_ce0_local = 1'b1;
    end else begin
        b_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_2_ce0_local = 1'b1;
    end else begin
        b_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_3_ce0_local = 1'b1;
    end else begin
        b_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        res_ce0_local = 1'b1;
    end else begin
        res_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        res_we0_local = 1'b1;
    end else begin
        res_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_0_address0 = zext_ln24_fu_255_p1;

assign a_0_ce0 = a_0_ce0_local;

assign a_1_address0 = zext_ln24_fu_255_p1;

assign a_1_ce0 = a_1_ce0_local;

assign a_2_address0 = zext_ln24_fu_255_p1;

assign a_2_ce0 = a_2_ce0_local;

assign a_3_address0 = zext_ln24_fu_255_p1;

assign a_3_ce0 = a_3_ce0_local;

assign add_ln24_1_fu_295_p2 = (ap_sig_allocacmp_indvar_flatten1_load + 4'd1);

assign add_ln24_fu_229_p2 = (ap_sig_allocacmp_i2_load + 3'd1);

assign add_ln46_2_fu_340_p0 = grp_fu_345_p3;

assign add_ln46_2_fu_340_p1 = grp_fu_353_p3;

assign add_ln46_2_fu_340_p2 = ($signed(add_ln46_2_fu_340_p0) + $signed(add_ln46_2_fu_340_p1));

assign add_ln49_fu_283_p2 = (tmp_fu_263_p3 + zext_ln49_fu_279_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_138 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_372 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln24_reg_432 == 1'd0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign b_0_address0 = zext_ln26_fu_271_p1;

assign b_0_ce0 = b_0_ce0_local;

assign b_1_address0 = zext_ln26_fu_271_p1;

assign b_1_ce0 = b_1_ce0_local;

assign b_2_address0 = zext_ln26_fu_271_p1;

assign b_2_ce0 = b_2_ce0_local;

assign b_3_address0 = zext_ln26_fu_271_p1;

assign b_3_ce0 = b_3_ce0_local;

assign i_fu_243_p3 = ((ap_phi_mux_icmp_ln264_phi_fu_198_p4[0:0] == 1'b1) ? add_ln24_fu_229_p2 : ap_sig_allocacmp_i2_load);

assign icmp_ln24_fu_307_p2 = ((ap_sig_allocacmp_indvar_flatten1_load == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_301_p2 = ((j_fu_289_p2 == 3'd4) ? 1'b1 : 1'b0);

assign j_fu_289_p2 = (select_ln24_fu_235_p3 + 3'd1);

assign res_address0 = zext_ln49_1_fu_336_p1;

assign res_ce0 = res_ce0_local;

assign res_d0 = add_ln46_2_fu_340_p2;

assign res_we0 = res_we0_local;

assign select_ln24_fu_235_p3 = ((ap_phi_mux_icmp_ln264_phi_fu_198_p4[0:0] == 1'b1) ? 3'd0 : ap_sig_allocacmp_j3_load);

assign tmp_fu_263_p3 = {{trunc_ln24_fu_251_p1}, {2'd0}};

assign trunc_ln24_fu_251_p1 = i_fu_243_p3[1:0];

assign zext_ln24_fu_255_p1 = i_fu_243_p3;

assign zext_ln26_fu_271_p1 = select_ln24_fu_235_p3;

assign zext_ln49_1_fu_336_p1 = add_ln49_reg_402_pp0_iter3_reg;

assign zext_ln49_fu_279_p1 = select_ln24_fu_235_p3;

endmodule //matrixmul
